version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - docker-compose up -d
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/*.jar
  discard-paths: yes