version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn package
      - zip -r rls_ci-0.0.1-SNAPSHOT.zip rls_ci-0.0.1-SNAPSHOT.jar .ebextensions .platform Procfile
artifacts:
  files:
    - rls_ci-0.0.1-SNAPSHOT.zip
  discard-paths: yes
