version: "3.5"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=q1w2e3
      - POSTGRES_DB=rls
